"""add_dt_ultimo_reset

Revision ID: 48b931d8774f
Revises: 927fbfa22d09
Create Date: 2026-04-14 00:03:55.959595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48b931d8774f'
down_revision: Union[str, Sequence[str], None] = '927fbfa22d09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pacientes', sa.Column('dt_ultimo_reset', sa.DateTime(), nullable=True))
    op.add_column('profissionais', sa.Column('dt_ultimo_reset', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profissionais', 'dt_ultimo_reset')
    op.drop_column('pacientes', 'dt_ultimo_reset')
    # ### end Alembic commands ###
