"""full_schema_v1

Revision ID: 5f034fe5f67d
Revises: 
Create Date: 2026-04-18 16:04:32.587448

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5f034fe5f67d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('especialidades',
    sa.Column('id_especialidade', sa.Uuid(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('is_livre_demanda', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id_especialidade')
    )
    op.create_table('municipios',
    sa.Column('id_municipio', sa.Uuid(), nullable=False),
    sa.Column('ibge', sa.String(length=7), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('nome_exibicao', sa.String(length=150), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('cor_primaria', sa.String(length=7), nullable=False),
    sa.Column('logo_url', sa.String(length=255), nullable=True),
    sa.Column('faltas_limite', sa.Integer(), nullable=False),
    sa.Column('config_absenteismo', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tema_visual', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('dt_cadastro', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id_municipio'),
    sa.UniqueConstraint('ibge'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('profissionais',
    sa.Column('id_profissional', sa.Uuid(), nullable=False),
    sa.Column('id_municipio', sa.Uuid(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('cpf', sa.String(length=11), nullable=False),
    sa.Column('conselho', sa.String(length=50), nullable=True),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('sn_ativo', sa.Boolean(), nullable=False),
    sa.Column('dt_cadastro', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_senha_provisoria', sa.Boolean(), nullable=False),
    sa.Column('dt_ultimo_reset', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_municipio'], ['municipios.id_municipio'], ),
    sa.PrimaryKeyConstraint('id_profissional'),
    sa.UniqueConstraint('id_municipio', 'cpf', name='uix_municipio_cpf')
    )
    op.create_table('unidades_saude',
    sa.Column('id_ubs', sa.Uuid(), nullable=False),
    sa.Column('id_municipio', sa.Uuid(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('cnes', sa.String(length=20), nullable=False),
    sa.Column('cep', sa.String(length=8), nullable=False),
    sa.Column('endereco', sa.String(length=255), nullable=False),
    sa.Column('dt_cadastro', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_municipio'], ['municipios.id_municipio'], ),
    sa.PrimaryKeyConstraint('id_ubs')
    )
    op.create_table('aux_especialidade_profissionais',
    sa.Column('id_profissional', sa.Uuid(), nullable=False),
    sa.Column('id_especialidade', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['id_especialidade'], ['especialidades.id_especialidade'], ),
    sa.ForeignKeyConstraint(['id_profissional'], ['profissionais.id_profissional'], ),
    sa.PrimaryKeyConstraint('id_profissional', 'id_especialidade')
    )
    op.create_table('aux_ubs_profissionais',
    sa.Column('id_ubs', sa.Uuid(), nullable=False),
    sa.Column('id_profissional', sa.Uuid(), nullable=False),
    sa.Column('permissoes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['id_profissional'], ['profissionais.id_profissional'], ),
    sa.ForeignKeyConstraint(['id_ubs'], ['unidades_saude.id_ubs'], ),
    sa.PrimaryKeyConstraint('id_ubs', 'id_profissional')
    )
    op.create_table('escala_central',
    sa.Column('id_escala', sa.Uuid(), nullable=False),
    sa.Column('id_municipio', sa.Uuid(), nullable=False),
    sa.Column('id_ubs', sa.Uuid(), nullable=False),
    sa.Column('id_profissional', sa.Uuid(), nullable=False),
    sa.Column('id_especialidade', sa.Uuid(), nullable=False),
    sa.Column('tp_dia_semana', sa.Integer(), nullable=False),
    sa.Column('hr_inicio', sa.Time(), nullable=False),
    sa.Column('hr_fim', sa.Time(), nullable=False),
    sa.Column('qt_atendimento', sa.Integer(), nullable=False),
    sa.Column('tempo_medio_min', sa.Integer(), nullable=False),
    sa.Column('is_disponivel_app', sa.Boolean(), nullable=False),
    sa.Column('sn_ativo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id_especialidade'], ['especialidades.id_especialidade'], ),
    sa.ForeignKeyConstraint(['id_municipio'], ['municipios.id_municipio'], ),
    sa.ForeignKeyConstraint(['id_profissional'], ['profissionais.id_profissional'], ),
    sa.ForeignKeyConstraint(['id_ubs'], ['unidades_saude.id_ubs'], ),
    sa.PrimaryKeyConstraint('id_escala')
    )
    op.create_table('log_auditoria',
    sa.Column('id_log', sa.Uuid(), nullable=False),
    sa.Column('id_usuario', sa.Uuid(), nullable=True),
    sa.Column('id_municipio', sa.Uuid(), nullable=True),
    sa.Column('metodo', sa.String(length=10), nullable=False),
    sa.Column('endpoint', sa.String(length=255), nullable=False),
    sa.Column('ip_origem', sa.String(length=50), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('dt_log', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_municipio'], ['municipios.id_municipio'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['profissionais.id_profissional'], ),
    sa.PrimaryKeyConstraint('id_log')
    )
    op.create_table('pacientes',
    sa.Column('id_paciente', sa.Uuid(), nullable=False),
    sa.Column('id_municipio', sa.Uuid(), nullable=False),
    sa.Column('id_ubs_referencia', sa.Uuid(), nullable=True),
    sa.Column('nr_cpf', sa.String(length=11), nullable=True),
    sa.Column('nr_cns', sa.String(length=15), nullable=True),
    sa.Column('nm_paciente', sa.String(length=150), nullable=False),
    sa.Column('nm_mae', sa.String(length=150), nullable=True),
    sa.Column('dt_nascimento', sa.Date(), nullable=False),
    sa.Column('tp_sexo', sa.String(length=1), nullable=False),
    sa.Column('contato', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sn_ativo', sa.Boolean(), nullable=False),
    sa.Column('is_validado_sus', sa.Boolean(), nullable=False),
    sa.Column('dt_aceite_lgpd', sa.DateTime(), nullable=False),
    sa.Column('dt_cadastro', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_senha_provisoria', sa.Boolean(), nullable=False),
    sa.Column('dt_ultimo_reset', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_municipio'], ['municipios.id_municipio'], ),
    sa.ForeignKeyConstraint(['id_ubs_referencia'], ['unidades_saude.id_ubs'], ),
    sa.PrimaryKeyConstraint('id_paciente')
    )
    op.create_table('agenda_central',
    sa.Column('id_agenda', sa.Uuid(), nullable=False),
    sa.Column('id_municipio', sa.Uuid(), nullable=False),
    sa.Column('id_escala', sa.Uuid(), nullable=False),
    sa.Column('dt_agenda', sa.Date(), nullable=False),
    sa.Column('sn_ativo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id_escala'], ['escala_central.id_escala'], ),
    sa.ForeignKeyConstraint(['id_municipio'], ['municipios.id_municipio'], ),
    sa.PrimaryKeyConstraint('id_agenda')
    )
    op.create_table('it_agenda_central',
    sa.Column('id_item', sa.Uuid(), nullable=False),
    sa.Column('id_municipio', sa.Uuid(), nullable=False),
    sa.Column('id_agenda', sa.Uuid(), nullable=False),
    sa.Column('hr_agenda', sa.Time(), nullable=False),
    sa.Column('id_paciente', sa.Uuid(), nullable=True),
    sa.Column('sn_encaixe', sa.Boolean(), nullable=False),
    sa.Column('tp_situacao', sa.String(length=2), nullable=True),
    sa.ForeignKeyConstraint(['id_agenda'], ['agenda_central.id_agenda'], ),
    sa.ForeignKeyConstraint(['id_municipio'], ['municipios.id_municipio'], ),
    sa.ForeignKeyConstraint(['id_paciente'], ['pacientes.id_paciente'], ),
    sa.PrimaryKeyConstraint('id_item')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('it_agenda_central')
    op.drop_table('agenda_central')
    op.drop_table('pacientes')
    op.drop_table('log_auditoria')
    op.drop_table('escala_central')
    op.drop_table('aux_ubs_profissionais')
    op.drop_table('aux_especialidade_profissionais')
    op.drop_table('unidades_saude')
    op.drop_table('profissionais')
    op.drop_table('municipios')
    op.drop_table('especialidades')
    # ### end Alembic commands ###
