"""feat_municipio_branding_e_travas

Revision ID: 83c95c5e5591
Revises: d17a913c53f2
Create Date: 2026-04-18 20:35:26.244194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83c95c5e5591'
down_revision: Union[str, Sequence[str], None] = 'd17a913c53f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
