"""novas_colunas

Revision ID: 927fbfa22d09
Revises: 3d62b4b86b37
Create Date: 2026-04-11 19:01:35.211911

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '927fbfa22d09'
down_revision: Union[str, Sequence[str], None] = '3d62b4b86b37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pacientes', sa.Column('is_senha_provisoria', sa.Boolean(), nullable=False))
    op.add_column('profissionais', sa.Column('is_senha_provisoria', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profissionais', 'is_senha_provisoria')
    op.drop_column('pacientes', 'is_senha_provisoria')
    # ### end Alembic commands ###
