"""Escalas Ciclo Definido

Revision ID: 96fe02a9a45e
Revises: fec8450b9d76
Create Date: 2026-04-21 19:28:46.176988

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96fe02a9a45e'
down_revision: Union[str, Sequence[str], None] = 'fec8450b9d76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('escala_central', sa.Column('dt_inicio', sa.Date(), server_default='2026-04-01', nullable=False))
    op.add_column('escala_central', sa.Column('dt_fim', sa.Date(), server_default='2026-12-31', nullable=False))
    op.add_column('escala_central', sa.Column('dt_disponibilidade', sa.Date(), server_default='2026-04-01', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('escala_central', 'dt_disponibilidade')
    op.drop_column('escala_central', 'dt_fim')
    op.drop_column('escala_central', 'dt_inicio')
    # ### end Alembic commands ###
