"""add_is_disponivel_app_em_escala

Revision ID: bbbffe68b211
Revises: 636268c66670
Create Date: 2026-04-03 16:27:32.905709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbbffe68b211'
down_revision: Union[str, Sequence[str], None] = '636268c66670'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # O server_default deve estar DENTRO do sa.Column(...)
    op.add_column('escala_central', sa.Column('is_disponivel_app', sa.Boolean(), nullable=False, server_default='true'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('escala_central', 'is_disponivel_app')
    # ### end Alembic commands ###
