"""add_senha_hash_to_paciente

Revision ID: d17a913c53f2
Revises: 5f034fe5f67d
Create Date: 2026-04-18 16:27:50.087594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd17a913c53f2'
down_revision: Union[str, Sequence[str], None] = '5f034fe5f67d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pacientes', sa.Column('senha_hash', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pacientes', 'senha_hash')
    # ### end Alembic commands ###
