"""Tabela Feriados

Revision ID: d9c2dc9437ea
Revises: 83c95c5e5591
Create Date: 2026-04-21 18:59:23.376654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9c2dc9437ea'
down_revision: Union[str, Sequence[str], None] = '83c95c5e5591'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feriados',
    sa.Column('id_feriado', sa.Uuid(), nullable=False),
    sa.Column('id_municipio', sa.Uuid(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('descricao', sa.String(length=150), nullable=False),
    sa.Column('tipo', sa.String(length=30), nullable=False),
    sa.Column('dt_cadastro', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_municipio'], ['municipios.id_municipio'], ),
    sa.PrimaryKeyConstraint('id_feriado'),
    sa.UniqueConstraint('id_municipio', 'data', name='uix_municipio_feriado_data')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('feriados')
    # ### end Alembic commands ###
