"""Add sn_bloqueia_feriados

Revision ID: fec8450b9d76
Revises: d9c2dc9437ea
Create Date: 2026-04-21 19:10:34.519034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fec8450b9d76'
down_revision: Union[str, Sequence[str], None] = 'd9c2dc9437ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('escala_central', sa.Column('sn_bloqueia_feriados', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('escala_central', 'sn_bloqueia_feriados')
    # ### end Alembic commands ###
